org: ${env:SLS_ORG} # Define SLS_ORG in .env
service: vegaway-sls

provider: ${file(./YAML/provider/provider.yml)}

functions:
  # CUSTOMER ACTIONS
  getMenu: ${file(./YAML/functions/customers/get-menu.yml)}
  createOrder: ${file(./YAML/functions/customers/create-order.yml)}
  getOrderStatus: ${file(./YAML/functions/customers/get-order-status.yml)}
  deleteOrder: ${file(./YAML/functions/customers/delete-order.yml)}
  updateOrder: ${file(./YAML/functions/customers/delete-order.yml)}

  # STAFF ACTIONS
  getOrders: ${file(./YAML/functions/staff/get-orders.yml)}
  updatePendingOrder: ${file(./YAML/functions/staff/update-pending-order.yml)}
  confirmPendingOrder: ${file(./YAML/functions/staff/confirm-pending-order.yml)}
  getInventory: ${file(./YAML/functions/staff/get-inventory.yml)}
  getStaffMenu: ${file(./YAML/functions/staff/get-staff-menu.yml)}
  updateMenuItem: ${file(./YAML/functions/staff/update-menu-item.yml)}

resources:
  Resources:
    MenuTable: ${file(./YAML/resources/tables/menu-table.yml)}
    OrdersTable: ${file(./YAML/resources/tables/orders-table.yml)}
    CognitoUserPoolClient: ${file(./YAML/resources/cognito-user-pool-client.yml)}
    CognitoUserPool: ${file(./YAML/resources/cognito-user-pool.yml)}
    CognitoIdentityPool: ${file(./YAML/resources/cognito-identity-pool.yml)}
    GuestUserRole: ${file(./YAML/resources/guest-user-role.yml)}
    AuthUserRole: ${file(./YAML/resources/auth-user-role.yml)}
    CognitoIdentityPoolRoleAttachment: ${file(./YAML/resources/cognito-identity-pool-role-attachment.yml)}
