org: ${env:SLS_ORG} # Define SLS_ORG in .env
service: vegaway-sls
custom:
  guestUserRole: ${file(./YAML/resources/guest-user-role.yml)}
  cognitoIdentityPool: ${file(./YAML/resources/cognito-identity-pool.yml)}

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: ${env:MY_ROLE_ARN} # Define MY_ROLE_ARN in .env
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
        - x-api-key
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      exposedResponseHeaders:
        - Special-Response-Header
      maxAge: 6000 # In seconds

functions:
  # CUSTOMER ACTIONS
  getMenu:
    handler: handlers/getMenu.handler
    events:
      - httpApi:
          path: /menu
          method: get
  createOrder:
    handler: handlers/createOrder.handler
    events:
      - httpApi:
          path: /orders
          method: post
  getOrderStatus:
    handler: handlers/getOrderStatus.handler
    events:
      - httpApi:
          path: /orders/status
          method: get
  deleteOrder:
    handler: handlers/deleteOrder.handler
    events:
      - httpApi:
          path: /orders
          method: delete
  updateOrder:
    handler: handlers/updateOrder.handler
    events:
      - httpApi:
          path: /orders
          method: put

  # STAFF ACTIONS
  getOrders:
    handler: handlers/getOrders.handler
    events:
      - httpApi:
          path: /staff/orders/{orderType}
          method: get
  updatePendingOrder:
    handler: handlers/updatePendingOrder.handler
    events:
      - httpApi:
          path: /staff/orders/pending
          method: put
  confirmPendingOrder:
    handler: handlers/confirmPendingOrder.handler
    events:
      - httpApi:
          path: /staff/orders/confirm
          method: post
  getInventory:
    handler: handlers/getInventory.handler
    events:
      - httpApi:
          path: /staff/inventory
          method: get
  getStaffMenu:
    handler: handlers/getStaffMenu.handler
    events:
      - httpApi:
          path: /staff/menu
          method: get
  updateMenuItem:
    handler: handlers/updateMenuItem.handler
    events:
      - httpApi:
          path: /staff/menu/items
          method: put

resources:
  Resources:
    # Imported resources first
    GuestUserRole: ${self:custom.guestUserRole}
    CognitoIdentityPool: ${self:custom.cognitoIdentityPool}
    # DynamoDB Resources
    MenuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-menu
        AttributeDefinitions:
          - AttributeName: menuId
            AttributeType: S
        KeySchema:
          - AttributeName: menuId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-orders
        AttributeDefinitions:
          - AttributeName: orderStatus
            AttributeType: S
        KeySchema:
          - AttributeName: orderStatus
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    # Cognito user pools
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: MyUserPool
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: MyUserPoolClient
        UserPoolId:
          Ref: CognitoUserPool
        GenerateSecret: false
        AllowedOAuthFlows:
          - code
        AllowedOAuthScopes:
          - email
          - openid
        CallbackURLs:
          - "http://localhost/*"
