org: ${env:SLS_ORG} # Define SLS_ORG in .env
service: vegaway-sls

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: ${env:MY_ROLE_ARN} # Define MY_ROLE_ARN in .env

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
