org: ${env:SLS_ORG} # Define SLS_ORG in .env
service: vegaway-sls

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: ${env:MY_ROLE_ARN} # Define MY_ROLE_ARN in .env

functions:
  # CUSTOMERS

  getMenu:
    handler: handlers/getMenu.handler
    events:
      - httpApi:
          path: /menu
          method: get

  sendOrder:
    handler: handlers/sendOrder.handler
    events:
      - httpApi:
          path: /sendOrder
          method: post

  getOrderStatus:
    handler: handlers/getOrderStatus.handler
    events:
      - httpApi:
          path: /getOrderStatus
          method: get

  deleteOrder:
    handler: handlers/deleteOrder.handler
    events:
      - httpApi:
          path: /deleteOrder
          method: delete

  updateOrder:
    handler: handlers/updateOrder.handler
    events:
      - httpApi:
          path: /updateOrder
          method: put

  # STAFF

  getActiveOrders:
    handler: handlers/getActiveOrders.handler
    events:
      - httpApi:
          path: /getActiveOrders
          method: get

  getPendingOrders:
    handler: handlers/getPendingOrders.handler
    events:
      - httpApi:
          path: /getPendingOrders
          method: get

  updatePendingOrder:
    handler: handlers/updatePendingOrder.handler
    events:
      - httpApi:
          path: /updatePendingOrder
          method: put

  confirmPendingOrder:
    handler: handlers/confirmPendingOrder.handler
    events:
      - httpApi:
          path: /confirmPendingOrder
          method: post

  getInventory:
    handler: handlers/getInventory.handler
    events:
      - httpApi:
          path: /getInventory
          method: get

  getMenuStaff:
    handler: handlers/getMenuStaff.handler
    events:
      - httpApi:
          path: /getMenuStaff
          method: get

  updateMenuItems:
    handler: handlers/updateMenuItems.handler
    events:
      - httpApi:
          path: /updateMenuItems
          method: put
